### ISSUE TITLE
Early return step needed for cancelled send()?

### ISSUE THREAD

**Issue by sof** [whatwg/xhr#101]
Step 10.{1,2} for an async send() ( https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send ) fire 'loadstart'(s). The event handling code could side-effect the state of the XHR object (calling abort() or re-initiate another send() by re-opening), should it so wish.

The spec doesn't _appear_ to account for that possibility upon return and continuing on to step 10.3.

This came up (indirectly) via https://crbug.com/642242

**Comment by annevk** [comment]
So I guess we basically want to check if the send() flag is set and that the state is still opened. Makes sense.

**Comment by sof** [comment]
You also need to account for the possibility that the handler could have done an(other) open() + send() over the object, I think.

**Comment by annevk** [comment]
So we'd need some counter? That sounds painful.

**Comment by sof** [comment]
We're not accommodating known-valuable behavior here (the ability to re-open during loadstart), so the dual of disallowing that somehow, is an option.

**Comment by annevk** [comment]
That's fair. @wisniewskit thoughts?

**Comment by annevk** [comment]
FWIW, I need to wait a little with fixing this until I sort out #97, so if this is high priority for you I'm happy with you telling me what you went with. I agree it probably does not matter much what we do here.

**Comment by sof** [comment]
ok, no rush. No changes made yet to address this issue in the Blink implementation, but stopping short the send() if the send flag is set or another fetch has been initiated upon return from a 'loadstart' dispatch, is probably worth putting in for now. If you decide to constrain what can happen during 'loadstart', I'd be quite happy to align the implementation right after.

**Comment by wisniewskit** [comment]
Thanks for pinging me, @annevk. I agree with the basic problem needing to be fixed. From what I'm reading, adding steps like these was basically the plan?
- send() 10.0.5: set the loadstartFiring flag (a new flag).
- send() 10.2.5: if state is not opened or send() flag is unset, then return. otherwise, unset the loadstartFiring flag.
- open() 1.5: if the loadstartFiring flag is set, throw an InvalidStateError exception.

**Comment by annevk** [comment]
Either that, or we add the ability to inspect whether a fetch is ongoing. That should also give us enough state I think (and allow `open()` to continue to be invoked whenever).

**Comment by sof** [comment]
https://chromium.googlesource.com/chromium/src/+/13c30eae8 adjusts the Blink handling of this loophole, so Chrome Canary builds should roll out (first) with that fix over the weekend. There's more to be done to make the implementation failsafe.

**Comment by sof** [comment]
(the worries i had wrt completeness of the bailout weren't real - changes to other parts of the XHR object state will be accurately reflected by the "send() flag" being reset at the same time.)

**Comment by annevk** [comment]
An alternative might be that we set the `send()` flag slightly later (after dispatching these events).

**Comment by annevk** [comment]
That seems to be what most implementations already expect... Writing some more tests...

**Comment by annevk** [comment]
> You also need to account for the possibility that the handler could have done an(other) open() + send() over the object, I think.

Or would we just let that turn into recursion? That seems to be what Firefox and Safari do.

**Comment by annevk** [comment]
I created tests for this. Based on those I still like my suggestion in https://github.com/whatwg/xhr/issues/101#issuecomment-261179776 best and not add any additional flags. If I missed something let me know.

**Comment by annevk** [comment]
Okay, @sof reviewed the tests and they seemed okay. Posted a PR now too. I don't think this ends up requiring any changes to browsers since they already did the right thing.
