### ISSUE TITLE
Should setting an invalid value to responseType on an XHR in LOADING/DONE state throw?

### ISSUE THREAD

**Issue by tyoshino** [whatwg/xhr#102]
The spec is not clear when the steps should be run.

https://heycam.github.io/webidl/#dfn-enumeration-value

> In the ECMAScript binding, assignment of an invalid string value to an attribute is ignored

Should we consider
- that the steps in the XHR spec are run only when the value is valid and therefore not ignored
- or that the steps in the XHR spec are run anyway, and invalid values are ignored in the step 4

(The interop issue was originally reported by Ali of Microsoft)

**Comment by annevk** [comment]
Do implementations actually do different things here?

As far as I can tell this is pretty clear. Binding code resolves before specification code, so no throwing.

**Comment by tyoshino** [comment]
Thank you, Anne. Yes, according to Ali, Edge is currently throwing, Firefox not, Chrome not. I'll ask Edge to align with us.

**Comment by annevk** [comment]
Sounds like Edge should implement IDL.
