### ISSUE TITLE
How should getResponseHeader() and getAllResponseHeaders() work

### ISSUE THREAD

**Issue by annevk** [whatwg/xhr#109]
Value separator: should likely become ", ", not ",".

Header casing: unclear, @youennf suggests lowercase is feasible.

Header sorting: unclear, different order among browsers suggests lexicographical might be feasible (this is what the standard requires at the moment).

Tests: https://github.com/w3c/web-platform-tests/pull/4641.

**Comment by annevk** [comment]
Todo: create a Fetch PR to add legacySpaceFlag to these two definitions.

**Comment by annevk** [comment]
I should note in the commit message that this also fixes a longstanding bug of `getAllResponseHeaders()` not including a final trailing CR LF.

**Comment by annevk** [comment]
Hmm, not even Safari TP implements these requirements. @youennf are you sure this is what WebKit wants? I'll file a bug I suppose to find out...

**Comment by annevk** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=169286 on WebKit.

**Comment by youennf** [comment]
Thanks for filing the bug.
STP is not yet doing the lowercasing but I plan to align it.

**Comment by annevk** [comment]
@wanderview @yutakahirano @tyoshino here as well your views would be appreciated.

**Comment by tyoshino** [comment]
Started a thread for Chrome regarding the lower casing part https://groups.google.com/a/chromium.org/d/topic/blink-dev/18I-rzEidQk/discussion

**Comment by tyoshino** [comment]
Regarding combining with 0x2C 0x20, I think Chrome would just follow that. Discussed at https://bugs.chromium.org/p/chromium/issues/detail?id=700434#c7.

**Comment by annevk** [comment]
Thanks @tyoshino!
