### ISSUE TITLE
indexing my site with my naanmani.wordpress.com in various places.

### ISSUE THREAD

**Issue by dhalapathy** [whatwg/xhr#111]
I got this error when i check inspect element.

JQMIGRATE: Migrate is installed, version 1.4.1
s0.wp.com/wp-includes/js/jquery/jquery.js:1 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by dhalapathy** [comment]
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ad_status.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by annevk** [comment]
You should contact the developer of the WordPress plugin.
