### ISSUE TITLE
Ensure progress events fired from "process response" always have a valid loaded value

### ISSUE THREAD

**Issue by KiChjang** [whatwg/xhr#118]
#90 ensures that progress events fired from "process request body" will always have a `loaded` value that is greater than (and not equal to) any prior event named progress for the request. However, progress events fired from "process response" are not guaranteed to have this property. We should fix this.

**Comment by annevk** [comment]
So thinking about this some more, there's only ever one "process response" and it's always the first. How could there be a prior progress event?

**Comment by KiChjang** [comment]
I can't seem to find the steps for "process response body" that you mentioned. Did you mean "process request body" instead?

"Process response" on subsubstep 10 is a recursive subsubstep that terminates until the *done* property is true, which would re-fire a progress event multiple times because of its subsubsubstep 5.

**Comment by annevk** [comment]
Sorry, I had forgotten "process response body" got replaced by streams. The same should have happened with "process request body" but that got overlooked. I just filed a bug against Fetch for that.

"Process response" is invoked once from Fetch and then its substeps in 10 are only invoked if new data is read from the stream, so they can't be invoked with no data whatsoever.

**Comment by KiChjang** [comment]
So following on with what you said, maybe we should also add a note to that step, saying that it is impossible to have a `e.loaded` value that is less than or equal to the previous firing of progress event?

**Comment by annevk** [comment]
I guess that's fair and I can create a PR. Are you happy to review PRs here?
