### ISSUE TITLE
Secure login landing on insecure page...not sure how to approach

### ISSUE THREAD

**Issue by abx901** [whatwg/xhr#134]
![screenshot 2017-03-30 at 9 53 25 am](https://cloud.githubusercontent.com/assets/23131465/24507563/9cce408c-1515-11e7-9258-574e23e886ea.png)
https://xhr.spec.whatwg.org/commit-snapshots/59c9cd9ae31fc8fafd1c327f2d2a1ca1e88da28f/#contents

**Comment by annevk** [comment]
I recommend first formulating a question and then asking it here: https://stackoverflow.com/.
