### ISSUE TITLE
Getting an warning "Synchronous XMLHttpRequest on the main thread is deprecated"

### ISSUE THREAD

**Issue by jcamp** [whatwg/xhr#135]
Hi

Using: xhr.open( 'GET', url, false );

Getting the following debugger error (warning actually):

"external.js:54 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience"

Any help appreciated. Using it in conjunction with reveal.js for slide shows.
Cheers

**Comment by annevk** [comment]
Basically, don't pass false as an argument. It creates a bad UX. https://stackoverflow.com/ is a better place for these type of questions though.
