### ISSUE TITLE
Update the getAllResponseHeaders() example

### ISSUE THREAD

**Issue by tyoshino** [whatwg/xhr#136]
https://xhr.spec.whatwg.org/#example-getresponseheaders must be updated by lower-casing names.

- https://github.com/whatwg/xhr/commit/ecce3904ace0dbe382a652ea1d8e29c7885fe8c4 made XHR switch to use sort and combine algorithm in the Fetch Standard.
- https://github.com/whatwg/fetch/pull/476 has reorganized algorithm in the Fetch Standard. As a side-effect, XHR's getAllResponseHeaders() started lower-casing names (see https://github.com/whatwg/fetch/pull/476#discussion_r100350231 and https://github.com/whatwg/xhr/issues/109).

https://github.com/w3c/web-platform-tests/pull/4641 has already added tests for wpt.

**Comment by annevk** [comment]
And also sorted names, right? PR coming up.

**Comment by tyoshino** [comment]
> And also sorted names, right?

Yes. Thanks!
