### ISSUE TITLE
Ajax is Not Working Online Server but Its work offline Localhost.

### ISSUE THREAD

**Issue by amitirizz** [whatwg/xhr#138]
Hii 
This is Amit From Mumbai, I am working on a cakephp project. I have developed some new functions and just uploaded to the online with correctly but by now Ajax with not working while I am going to Save my data.....

What is the Issue for that

**Comment by annevk** [comment]
No idea. You could maybe try https://stackoverflow.com/ but you'll have to be way more specific in asking your question.
