### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by shitalsunilsulakhe** [whatwg/xhr#140]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience how to solve this error

**Comment by annevk** [comment]
Yes it is!

**Comment by shitalsunilsulakhe** [comment]
how to resolve it

**Comment by annevk** [comment]
How to rewrite existing code is best asked on https://stackoverflow.com/. This forum is for discussing the standard itself.
