### ISSUE TITLE
does "remote address"  in xhr response standard ?

### ISSUE THREAD

**Issue by dj31416** [whatwg/xhr#156]
I wonder know is there any method to get  "Remote Address" of general header ?
![heder2](https://user-images.githubusercontent.com/5155540/31109179-bfbd35ae-a830-11e7-9006-405606557790.png)

thanks

**Comment by annevk** [comment]
There's no such API and it seems that introducing one would violate the same-origin policy. You could make the server return it though in a custom response header or some such.

**Comment by dj31416** [comment]
got it! thanks!
