### ISSUE TITLE
Look at overrideMimeType() again

### ISSUE THREAD

**Issue by annevk** [whatwg/xhr#157]
There's a test that checks that `text/xml;charset=†` is rejected and Chrome has implemented this, but I don't think any other part of the platform reuses that check. What we end up doing is ignoring non-ASCII bytes in MIME types. So we should rewrite `XMLHttpRequest/overridemimetype-blob.html` and maybe change the requirements in the specification.

This ties into the ever growing https://github.com/whatwg/mimesniff/issues/30.

See https://bugzilla.mozilla.org/show_bug.cgi?id=918731 for more background.

**Comment by annevk** [comment]
The tentative plan here is that `overrideMimeType()` invokes the MIME type parser and stores the MIME type record result (rather than the bit without parameters). That means this will build on top of https://github.com/whatwg/mimesniff/pull/36.

**Comment by domenic** [comment]
Note that I think right now this does not properly translate charset from an encoding label to an encoding name, although I haven't properly traced through how override charset is used to figure out if maybe using a label is OK.

**Comment by annevk** [comment]
Hmm yeah, it'd be good to test that as part of #174. In particular if unrecognized labels get skipped somehow. I'll be away for two weeks so probably won't get around to it until I'm back.
