### ISSUE TITLE
I think I have a bug

### ISSUE THREAD

**Issue by Snazzypeanuts** [whatwg/xhr#170]
What and how do I get the required information on here to report a bug?

**Comment by Snazzypeanuts** [comment]
[SmartyPants Readme.txt](https://github.com/whatwg/xhr/files/1439951/SmartyPants.Readme.txt)

**Comment by annevk** [comment]
Basically you review https://xhr.spec.whatwg.org/ and if you spot a mistake you detail that in an issue.
