### ISSUE TITLE
Parse string as FormData

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/xhr#180]
Right now you have to do:

```js
const formData = await new Response(str).formData();
```

Feels like there should be a way to directly parse a string as form data.

Probably low priority, but noticed it while writing a test.

**Comment by jakearchibald** [comment]
Ignore me. The above doesn't work, as it needs the header.

**Comment by annevk** [comment]
It's probably worthwhile to have this for `multipart/form-data` though.

cc @bsittler
