### ISSUE TITLE
The xhr logo appears to be copied from AFC Ajax (Dutch soccer club)

### ISSUE THREAD

**Issue by tdons** [whatwg/xhr#186]
The logo used for xhr looks similar to that of AFC Ajax' logo (a Dutch soccer club)

Compare:
https://resources.whatwg.org/logo-xhr.svg

To:
https://en.wikipedia.org/wiki/AFC_Ajax#/media/File:Ajax_Amsterdam.svg

Is this known?  Is this OK in terms of copyright, etc.?

Just checking.

**Comment by annevk** [comment]
It's a joke; see https://en.wikipedia.org/wiki/Ajax_(programming). Our hope is that it falls under fair use therefore, but we haven't sought legal advice on the matter. If they were to complain we'd probably change it.

**Comment by tdons** [comment]
I got the reference ;-)

Since you know I’ll close the issue.
