### ISSUE TITLE
Please add followRedirects=true/false to XMLHttpRequest specification

### ISSUE THREAD

**Issue by Nadya678** [whatwg/xhr#189]
Please add followRedirects=true/false to XMLHttpRequest specification. Without it there is no possible to catch in onreadystatechange redirection pages (301 and 302 status) and response of them or optionally state 5 in .readyState with possibility of read status code, response and headers. 

Default value of followRedirects for compatibility: true.

**Comment by annevk** [comment]
We're not extending XMLHttpRequest. Please use `fetch()` instead, which offers this feature to some extent (cannot reveal too much about redirects for security reasons).
