### ISSUE TITLE
How is the about:blank case in send-non-same-origin supported by the spec?

### ISSUE THREAD

**Issue by wisniewskit** [whatwg/xhr#194]
I'm not seeing any reason in spec-text for the `about:blank` test in the `/xhr/send-non-same-origin.htm` WPT to pass. As far as I can tell, the XHR spec does nothing special for about:blank, it just does its usual fetch. Fetch should therefore do a scheme fetch, where about:blank is special-cased to succeed as a 0-byte response with a single content-type header. However, according to wpt.fyi browsers mostly agree with the test-case, and throw a NetworkError instead (aside from Edge).

**Comment by annevk** [comment]
In https://fetch.spec.whatwg.org/#main-fetch step 5 it'll match on "request’s current url’s scheme is not an HTTP(S) scheme" which results in a network error.

**Comment by wanderview** [comment]
Interestingly, firefox and edge both allow `fetch("about:blank")`.  Chrome rejects on it.  I don't have a mac handy to test webkit.

**Comment by annevk** [comment]
Note that I added this test in https://github.com/w3c/web-platform-tests/pull/5155, but I'm guessing I had not quite internalized a policy yet of filing bug reports. In any event, I suggest Edge and Firefox fix this. (Safari rejects with a TypeError as per the specification.)

**Comment by wanderview** [comment]
We pass that test because its checking xhr instead of fetch().  It seems we have an extra check in the xhr code that our fetch() code is missing.

**Comment by wisniewskit** [comment]
@wanderview, it actually looks like the Firefox fetch code is [intentionally allowing about:blank through](https://searchfox.org/mozilla-central/source/dom/fetch/FetchDriver.cpp#479). It looks like it was added in  [bug 1216687](https://bugzilla.mozilla.org/show_bug.cgi?id=1216687), but I don't see any notes as to why.

**Comment by annevk** [comment]
I found http://w3c-test.org/fetch/api/basic/scheme-about.any.html for `fetch()`, which Chrome and Safari fail. I'll update that test so we consistently disallow `about:blank` here and I'll file a bug against Edge and Firefox.
