### ISSUE TITLE
getResponseHeader should work case-insensitive

### ISSUE THREAD

**Issue by edwinvanderham** [whatwg/xhr#21]
Currently, the spec does not state anything about case-sensitivity with respect to response header names. In the W3C version of the spec (http://www.w3.org/TR/XMLHttpRequest/#the-getresponseheader()-method) it is stated that a header is a case-insensitive match for a response header.

To me it makes more sense to ignore the case in matching response headers.

**Comment by Ms2ger** [comment]
This is covered in Fetch: https://fetch.spec.whatwg.org/#concept-header
