### ISSUE TITLE
typo (no timeout after load)

### ISSUE THREAD

**Issue by Mouvedia** [whatwg/xhr#217]
> <TimothyGu\> Could you file an issue?

https://github.com/whatwg/xhr/commit/972797fb12106ca00292b9a2e2cb91d8766c4640#r29848015

**Comment by annevk** [comment]
I think completed is fine here, since we don't know if the request will succeed or fail.

**Comment by annevk** [comment]
@TimothyGu I guess you had a different perspective on that?

**Comment by Mouvedia** [comment]
You are using the term "completed" for `onloaded` which means `abort` can fire after `onload`; surely that's not desired?

**Comment by annevk** [comment]
This table has no normative meaning, it just summarizes a bunch of details. "Completed" just means that the fetch is over with.

**Comment by TimothyGu** [comment]
@annevk Nah I wasn't sure if this was an actual bug or no so I just asked @Mouvedia to file an issue.

**Comment by Mouvedia** [comment]
@annevk it's unclear and was incorrectly implemented before: https://bugzilla.mozilla.org/show_bug.cgi?id=703380

**Comment by annevk** [comment]
@Mouvedia that bug doesn't cite the specification as being problematic though. And again, it's a non-normative summary that implementers shouldn't really consult anyway.

I suppose we could add a paragraph after the table: "The abort, error, load, and timeout events are mutually exclusive." Would that help?

**Comment by Mouvedia** [comment]
> I suppose we could add a paragraph after the table: "The abort, error, load, and timeout events are mutually exclusive." Would that help?

That would be even more confusing. Forget about it.
