### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Rayiito** [whatwg/xhr#24]
![untitled](https://cloud.githubusercontent.com/assets/13796269/9272465/426bf2c6-42b5-11e5-91d3-96effe99d832.png)
What does this mean?

**Comment by annevk** [comment]
It means you should not use synchronous XMLHttpRequest.

**Comment by Rayiito** [comment]
so what do I need to do?
is this a problem? or I'll just let it be

**Comment by annevk** [comment]
You should use events and not use the third parameter of the `open()` method. Best to ask these type of questions on https://stackoverflow.com/ though.

**Comment by Rayiito** [comment]
you see , the problem is im not good with these type of things and i dont know what to do

**Comment by tyoshino** [comment]
See http://blogs.msdn.com/b/wer/archive/2011/08/03/why-you-should-use-xmlhttprequest-asynchronously.aspx by Microsoft, https://developer.mozilla.org/ja/docs/XMLHttpRequest/Synchronous_and_Asynchronous_Requests by Mozilla for example to understand why sync XHRs have been considered to be bad.

You can find some resources about how to migrate your code using sync XHR to async XHR in Japanese for example by searching for "同期 XMLHttpRequest", "同期 XMLHttpRequest 非推奨", ...
