### ISSUE TITLE
Creating an ArrayBuffer can fail

### ISSUE THREAD

**Issue by annevk** [whatwg/xhr#26]
When a new `ArrayBuffer` object is created this can throw a `RangeError`. We need to decide how to deal with that.

Gecko throws the exception from the `response` getter as long as allocation keeps failing. But it might be simpler to return null. That means developers won't have to expect exceptions from using a simple getter and don't have to write complicated code to keep trying to get an `ArrayBuffer` allocated in a loop.

**Comment by bzbarsky** [comment]
So return null and then keep returning null thereafter?  As in, once you fail to get the data, you're never going to get it, even if you free up some memory?

It does have the benefit of consistency....

**Comment by bzbarsky** [comment]
Oh, and I guess the spec actually defines the lazy allocation behavior inside the `response` getter that Gecko has, so at least that part will be consistent...

**Comment by annevk** [comment]
Yeah, once you fail to get the data you won't get it unless you fetch it again and get lucky.

**Comment by annevk** [comment]
That's what happens for `fetch()` too since it effectively tries to consume the stream and then create the `ArrayBuffer` with the result. If you cannot create the `ArrayBuffer`, you cannot really unconsume the stream either (not that that even makes sense).

**Comment by tyoshino** [comment]
Currently, Chrome crashes when it fails to allocate an ArrayBuffer as it wasn't specified to throw an exception in the spec at the time we decided how to handle the case.

Unless there'll be any confusion, returning null should be fine. What's the reliable way to distinguish alloc failure and other errors (network error)? Saw "load" being dispatched, but seeing null on response?

+1 to Boris regarding consistency.

**Comment by annevk** [comment]
@tyoshino, yeah, I guess that would be the way they get distinguished indeed.

**Comment by sof** [comment]
If allocation of the underlying buffer fails, https://xhr.spec.whatwg.org/#arraybuffer-response tells us to return a `null` response object, along with resetting 'received  bytes' to empty. Doesn't that imply that the next property access of `response` will return an empty array buffer, and not `null` - is that intentional?

(This came up via https://codereview.chromium.org/2730943002/ )

**Comment by annevk** [comment]
Yeah that is broken. Proposal: response object can be an object, failure, or null and we update all the places that use it accordingly. I don't think we can get away with not using some extra state somehow.
