### ISSUE TITLE
Korean translation document.

### ISSUE THREAD

**Issue by Djunnni** [whatwg/xhr#266]
Hi, i will translate this to Korean translation document.
how to pull request here at finished?

**Comment by annevk** [comment]
Wow, that's great!

Thus far translations have hosted their own copy, either on GitHub or elsewhere, and we'd link it from the main standard. Currently `xhr.bs` links to a Japanese translation as follows:

`Translation: ja https://triple-underscore.github.io/XHR-ja.html`

Is that workable or would you prefer some other arrangement?

**Comment by Djunnni** [comment]
thanks. good :)

**Comment by annevk** [comment]
@Djunnni hey, is this still something you are pursuing or shall we close this issue?
