### ISSUE TITLE
ReadableStream appears incompatible with Sync XHR

### ISSUE THREAD

**Issue by gterzian** [whatwg/xhr#277]
Looking at Step 12 of https://xhr.spec.whatwg.org/#the-send()-method. 

So at step 12.2, I think the task on the event-loop from where the call originates "blocks" on the "fetch" call returning a response. 

Then the problem I have run into is that as part of fetch, we have to [transmit the request body](https://fetch.spec.whatwg.org/#concept-request-transmit-body), which I think requires running code on the event-loop(although that is actually a question I've asked at https://github.com/whatwg/fetch/issues/976). 

So in other words, in order to transmit the request body of the fetch, we need to read from the stream, which, at least if the body is a user provided stream, will require running code on an event-loop. It that event-loop is the same that is currently blocking on the fetch call as part of a sync XHR, it appears to be an actual deadlock. 

I'm actually running into this very problem while integrating streams into the Servo project(see https://github.com/servo/servo/pull/25873#issuecomment-635093084). 

One potential solution, both at the level of the spec and as a practical solution, could be to add a new step prior to step 12.2(the fetch call), where one would acquire a reader, and then read all the chunks from the stream, and then use the bytes directly to transmit the body as part of the fetch. 
Although I think this could raise some issues because reading chunks from the stream could potentially result in the user stream code running, which would mean the XHR wouldn't be really "sync" anymore.

**Comment by annevk** [comment]
I see two solutions I like a bit better as I don't really care for XMLHttpRequest:

* We use a more limited form of BodyInit for XMLHttpRequest
* We throw when you pass a ReadableStream and the synchronous flag is set.

Note that upload streams in general still have issues that are being sorted out in the Fetch repository.

cc @yutakahirano

**Comment by yutakahirano** [comment]
> So in other words, in order to transmit the request body of the fetch, we need to read from the stream, which, at least if the body is a user provided stream, will require running code on an event-loop. It that event-loop is the same that is currently blocking on the fetch call as part of a sync XHR, it appears to be an actual deadlock.

I'm confused by this paragraph, as for XHR there is no user provided stream.

**Comment by annevk** [comment]
@yutakahirano there is, `send()` takes `BodyInit` which consists of `ReadableStream` among other things.

**Comment by yutakahirano** [comment]
Oh sorry I missed that, thank you. Then I prefer removing that functionality from XHR. I'm not sure if which of throwing or ignoring is better.

**Comment by gterzian** [comment]
Makes sense, strictly speaking even in the other `BodyInit` cases those objects are [extracted into a stream](https://fetch.spec.whatwg.org/#concept-bodyinit-extract), and those could be said to be fully "native" streams where reading chunks would not require calling into JS.

**Comment by gterzian** [comment]
On the other hand, returning an error in the stream case allows us to still use `BodyInit`, versus adding a new IDL like `XhrBodyInit` that would not include a stream...

**Comment by annevk** [comment]
Thinking about it more I suspect implementations don't support this today and what happens is that ReadableStream gets stringified. That's acceptable to me.

I would suggest we define XMLHttpRequestBodyInit in Fetch and define BodyInit as (ReadableStream or XMLHttpRequestBodyInit). And make XMLHttpRequest use (Document or XMLHttpRequestBodyInit).

ReadableStream will stringify in IDL land and then be treated as a string in XMLHttpRequest as a result.

**Comment by gterzian** [comment]
Ok I'll take it on, starting with the change in Fetch then.
