### ISSUE TITLE
Typo: "fire an progress event named e"

### ISSUE THREAD

**Issue by riverspirit** [whatwg/xhr#30]
https://xhr.spec.whatwg.org/#firing-events-using-the-progressevent-interface

>  fire **an** progress event named e ==> fire **a** progress event named e

**Comment by annevk** [comment]
Thank you. How would you like to appear in the acknowledgments? As jsx?

**Comment by riverspirit** [comment]
It was a small typo. So no need of acknowledgement. But thank's for asking :)

**Comment by annevk** [comment]
Every contribution gets acknowledged normally, without judgment about whether that is a small or large contribution. Would make things too difficult. But you can still opt-out, of course.
