### ISSUE TITLE
Consider setting omit-Origin-header-flag for same origin requests

### ISSUE THREAD

**Issue by tyoshino** [whatwg/xhr#31]
Created in response to https://github.com/whatwg/fetch/issues/91#issuecomment-159190323.

As @yutakahirano reported in https://github.com/whatwg/fetch/issues/91#issuecomment-144348029, Chrome (only GET/HEAD) and Firefox (also for POSTs) are not sending the `Origin` header for same origin requests. The background for Chrome (WebKit) is a little complicated (see https://github.com/whatwg/fetch/issues/91#issuecomment-128261982).

As it's been so for long time, we could make XHR an exception (i.e. no Origin for same origin requests).

**Comment by tyoshino** [comment]
See also https://github.com/whatwg/fetch/issues/172

**Comment by annevk** [comment]
So it seems we need something more complicated since a same-origin to cross-origin redirect as initial response would cause the header to be included, right?

**Comment by tyoshino** [comment]
I think so. If we adopt the change, i.e. no Origin header for same-origin, we should align Origin header inclusion yes/no with cross origin yes/no. When we enter cross-origin processing state in response to same to cross redirect, we should include the Origin header in the next, now cross-origin, request.

**Comment by tyoshino** [comment]
Maybe `HTTP-network-or-cache fetch` should be passed `CORS flag` and use it to decide whether or not to append the Origin header.

**Comment by annevk** [comment]
The problem is that we also use the `Origin` header for `<form method=POST>` and some other things? What logic does Blink use at the moment?

**Comment by tyoshino** [comment]
It's complicated. @hiroshige-g is checking Blink code to sort it out now.

**Comment by wanderview** [comment]
Related gecko bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1272302

**Comment by annevk** [comment]
FWIW, this is being fixed by https://github.com/whatwg/fetch/issues/225. We're just obsoleting the need for the flag and instead directly check the methods in use (or the CORS flag).
