### ISSUE TITLE
Handle error while reading response body in synchronous XHR

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/xhr#314]
Currently the error is ignored, which is not good.

**Comment by annevk** [comment]
I guess I also need to test the asynchronous case as basically https://xhr.spec.whatwg.org/#handle-errors doesn't make a whole lot of sense. Or do we already have tests for that?

**Comment by mobinskyman** [comment]
در تاریخ چهارشنبه ۳ مارس ۲۰۲۱،‏ ۱:۱۰ ب.ظ Anne van Kesteren <
***@***.***> نوشت:
