### ISSUE TITLE
features request:add SynXMLHttpRequest for Avoid Callback Hell Programming

### ISSUE THREAD

**Issue by annopnod** [whatwg/xhr#323]
Avoid Callback Hell Programming from XMLHttpRequest

**Add New Function**

**SynXMLHttpRequest**

var xml=new SynXMLHttpRequest() ;
xml.open('GET', 'test.php');
xml.send(FormData);
var rs=JSON.parse(xml.result);
console.log(rs);

**Comment by annevk** [comment]
Use `fetch()` and async/await.
