### ISSUE TITLE
Allow to send body within GET http requests

### ISSUE THREAD

**Issue by VitaliiOdiichuk** [whatwg/xhr#351]
As per [spec](https://httpwg.org/specs/rfc7231.html#GET) GET request is not prohibited to have a body please allow set not empty body for GET requests.

**Comment by domenic** [comment]
Dupe of https://github.com/whatwg/fetch/issues/83.

**Comment by Gerard19742608jourdain** [comment]
> As per [spec](https://httpwg.org/specs/rfc7231.html#GET) GET request is not prohibited to have a body please allow set not empty body for GET requests.
