### ISSUE TITLE
XHR using sync warning

### ISSUE THREAD

**Issue by TheJaredWilcurt** [whatwg/xhr#40]
https://xhr.spec.whatwg.org/#sync-warning

> Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user's experience. 

Despite there being many, many cases in which synchronous results are preferred and would not be detrimental to the user's experience, clearly, this nonsense is happening anyway. So... why not put a link to a page offering alternative solutions to how to use Async XHR in a manner that satisfies the common needs of what Sync XHR would be used for. Rather than just saying "don't do that", you should say "do this instead". Don't take things away without offering replacements.

**Comment by caitp** [comment]
See #20, this may not actually be able to happen, unfortunately

**Comment by annevk** [comment]
If you have some suggestions I'd be happy to consider them, but generally a specification is not a tutorial for writing decent apps.
