### ISSUE TITLE
Ajax call to server in synchronous mode <> disrupt user experience!

### ISSUE THREAD

**Issue by Vinhold** [whatwg/xhr#43]
https://xhr.spec.whatwg.org/#sync-warning

I just had Google Chrome block my ajaxObj.open('POST','StdGradReSet.aspx',false); because it was synchronous and would "disrupt the user experience". I have built an online web application program that depends on this action being synchronous as it is a modal state required to prevent data corruption in the program. If the server is being a bit slow, that is expected in this case and is not a problem. What is a disruption of the "user experience" is blocking the call and preventing the operation from taking place even if it is "slow" by a second or two. I understand this problem in some web site cases uses, but that does not apply in a full application program where modal action is required. If the server is slow in responding that is a server management issue, not a browser enforcement problem. At this point in time, the ajax object .open command does not have a timeout option in it that can be set and handled within the command itself, or any way to set the modal action on intent. Please provide an alternative option in the command to explicitly determine modal action and not block it. Band-aiding this  by forcing asynchronous processing and use of the .onreadystatechange event only causes data corruption problems for data processing applications.

Bob Curtice
Web Software Developer

**Comment by annevk** [comment]
It does actually apply to all applications. Anyway, this issue is already filed as #20.
