### ISSUE TITLE
"For the purposes of interaction with other algo..."

### ISSUE THREAD

**Issue by bakulf** [whatwg/xhr#48]
https://xhr.spec.whatwg.org/#interface-formdata

> For the purposes of interaction with other algorithms, an entry's type is "string" if its value is a string and "file" otherwise\. If an entry's type is "file", its filename is "blob" if value is not a File object, and otherwise its filename is the value of entry's value's name attribute\. 

I don't see any good reason to force 'blob' as filename here: a File can have an empty name, and a HTMLInputElement type=file, if not set, contains a blob without name. This makes an inconsistent behavior between a form submission and FormData.

**Comment by annevk** [comment]
Thank you!
