### ISSUE TITLE
Document responses and responseXML should be null in workers

### ISSUE THREAD

**Issue by Manishearth** [whatwg/xhr#51]
Workers shouldn't have access to `Document` objects, and WPT even tests for this in workers/semantics/xhr/001.html, however the spec doesn't seem to say anything about `response` (where `responseType=="document"`) and `responseXML` when being evaluated from a worker context.

Perhaps we should be early-returning null in both cases?

**Comment by annevk** [comment]
Well, `responseXML` isn't exposed in workers due to IDL. As for `resonseType`, how where you planning on setting that to "`document`" in a worker context?

**Comment by Manishearth** [comment]
Oh, my bad, the handling was in the `Exposed`.

I thought the spec was missing this because I forgot that Servo doesn't implement `Exposed` :smile:

**Comment by annevk** [comment]
No worries, happy to help.
