### ISSUE TITLE
What is the difference between url and current url?

### ISSUE THREAD

**Issue by KiChjang** [whatwg/xhr#52]
https://fetch.spec.whatwg.org/#concept-request-url
https://fetch.spec.whatwg.org/#concept-request-current-url

Can it be understood as url being the first URL that is added into the [url list](https://fetch.spec.whatwg.org/#concept-request-url-list), while the current url is the URL that is most recently added into url list?

**Comment by annevk** [comment]
Yes.

**Comment by KiChjang** [comment]
Whoops, just noticed that this is opened at the wrong repo, closing this.
