### ISSUE TITLE
abort() handling of state is busted

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/xhr#54]
Consider this testcase:

    var xhr = new XMLHttpRequest();
    xhr.open("GET", "data:text/plain,");
    console.log(xhr.readyState);
    xhr.send();
    xhr.onreadystatechange = function() {
      xhr.onreadystatechange = null;
      xhr.open("GET", "data:text/plain,hello");
      xhr.onload = function() { alert(xhr.responseText); }
      xhr.send();
    }
    xhr.abort();
    console.log(xhr.readyState);

per the letter of the current spec, this should log 1 then 0.  And it should alert "hello".  This is the behavior I see in Blink and WebKit.  However, this means that after the abort() call the readyState is 0 but there is a load in progress.  That's the busted part.

Gecko has a guard in abort() step 3 and only reset the state to "unsent" if it's still "done" after the request error steps and all their events have terminated.  This leaves state as a correct reflection of the actual state of the object.

**Comment by annevk** [comment]
This was fiddled with last in https://github.com/whatwg/xhr/commit/2cbfaec51a119dd4c92de1d869c01b6fe725b3db as far as I can tell, but unfortunately we did not have the practice of pointing to rationale back then.

**Comment by annevk** [comment]
I have created a PR for a fix, but I cannot land it until #57 is fixed.

**Comment by hallvors** [comment]
Sweet little test you've got there Boris, you haven't added it to the test suite I suppose?
This is such a corner case I'll be surprised if any existing tests need updating..

**Comment by bzbarsky** [comment]
I don't think I added a test for this, no; back when I filed the issue it wasn't clear to me which way the spec would go here.  Do you want to add one, or should I?

**Comment by hallvors** [comment]
I'll add it :)

**Comment by hallvors** [comment]
We had https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/open-during-abort.htm which is pretty close - just lacks a send().  
New test: https://github.com/w3c/web-platform-tests/commit/51f30d010fab9995fa8c8af47a1accf2261dfdd8

**Comment by hallvors** [comment]
(obviously great if @bzbarsky can check that the test captures what he had in mind..)

**Comment by bzbarsky** [comment]
Yep, that looks good!
