### ISSUE TITLE
Fix Fetch integration

### ISSUE THREAD

**Issue by annevk** [whatwg/xhr#57]
Currently building XMLHttpRequest fails because Fetch changed a few things around due to Streams integration.

@yutakahirano you were going to fix that, right?

**Comment by yutakahirano** [comment]
Sorry for the delay, I will do.

**Comment by annevk** [comment]
Hey @yutakahirano, do you have an estimate for when you'll get to this?

**Comment by yutakahirano** [comment]
I'm working at https://github.com/whatwg/xhr/tree/fetch-streams and I will send the change for the initial review by tomorrow.

**Comment by annevk** [comment]
Great, thank you!
