### ISSUE TITLE
null for response in case of invalid JSON

### ISSUE THREAD

**Issue by dmikis** [whatwg/xhr#68]
[JSON body parsing algorithm](https://xhr.spec.whatwg.org/#json-response) states that trying to parse a response which is an invalid JSON (thus, making `JSON.parse` throw an exception) will result in setting `null` to the `response` property. But according to ECMA-404 (but not to [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt)), `null` is a valid JSON. So there is no way to distinct a valid response containing `null` and an invalid JSON.

**Comment by annevk** [comment]
You didn't like my earlier suggestion? `XMLHttpRequest` is effectively frozen. We'll fix bugs and regressions and such, but all effort is put into `fetch()`, which incidentally doesn't have this problem.

**Comment by dmikis** [comment]
No, the suggestion seems perfectly fine:) I've just inferred from your answer that WHATWG spec is supported and just W3C one is frozen.

`fetch` behaviour in the described case is fine.

**Comment by annevk** [comment]
Ah yeah, it is supported, but no new features for `XMLHttpRequest`.

**Comment by dmikis** [comment]
Strictly speaking it's not a new feature, it's an existing behaviour that seems erroneous due to an ambiguous situation (however, I agree, a bit theoretical).
