### ISSUE TITLE
Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by versdivers** [whatwg/xhr#69]
Hello

My checkout page won't continue because i have the following error :
![image](https://cloud.githubusercontent.com/assets/18028151/14836372/e3fdb150-0c0f-11e6-8f86-d4c4809798e0.png)

Any idea?

**Comment by jdm** [comment]
The highlighted text is merely a warning; it does not indicate that the request should behave any differently than expected. The fact that it links to this specification is merely for informational purposes; you should look elsewhere for browser-specific web development assistance.

**Comment by versdivers** [comment]
I am trying to address as many possibility's as possible. Thank you for your responding. I hope someone somewhere can help me.

**Comment by annevk** [comment]
That looks like a server issue. Not something we can help with. You should also look into HTTPS. Handling customer data without it is irresponsible at this point.
