### ISSUE TITLE
what is the problem

### ISSUE THREAD

**Issue by rajendra4503** [whatwg/xhr#70]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

**Comment by caitp** [comment]
<over-simplified explanation>JS runs in the UI thread, and network requests can take a long time to finish. So you're blocking the UI thread, and most interactions the user makes with the site will not be responsive. If the network request takes a long time, this produces a terrible user experience, for no good reason.

**Comment by annevk** [comment]
This is a duplicate of #20 as far as I can tell. Let me know if you disagree, thanks!
