### ISSUE TITLE
Should we be pinning Blob URIs on fetches?

### ISSUE THREAD

**Issue by Manishearth** [whatwg/xhr#79]
Ref https://github.com/w3c/web-platform-tests/blob/master/FileAPI/blob/Blob-XHR-revoke.html

``` js
    var blob = new Blob(["test"]);
    var url = URL.createObjectURL(blob);
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url);

    URL.revokeObjectURL(url);
    xhr.onload = function() {console.log(xhr.response)}
    xhr.send();
```

Firefox has interesting behavior when it comes to revoked blob URIs.

If, for example, you call `xhr.open()` on  a nonrevoked blob URI, that URI can be fetched via XHR even after it is revoked. Newer fetches (via XHR or otherwise) cannot access it, however, only fetches opened before the revocation.

Additionally, calling `xhr.open()` on a revoked URI will error. I'm not so fond of this behavior myself, I don't think `open()` should be erroring on valid but nonexistant URIs since that can be unexpected behavior -- it should instead wait for the `send()` and error then.

We should discuss getting some or all of this behavior into the spec, or removing it if not desired.

cc @izgzhen @baku @annevk

**Comment by annevk** [comment]
That the URL can be fetched later is defined. The URL parser clones the `Blob` after all.

That `open()` errors or where we error exactly for closed blobs is not. If someone can work out what would be best there, including how that should work for `FormData` and the streaming case of directories I'd be most grateful. I agree though that failure for that should probably not happen during `open()`...

**Comment by annevk** [comment]
@mkruisselbrink @inexorabletash thoughts? What is the story for closed blobs these days?

**Comment by annevk** [comment]
Closed blobs are gone, but I created a WPT PR for the issue mentioned in OP. I think this is all defined already through the combination of URL and Fetch.

**Comment by annevk** [comment]
Bugs filed:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1341609
* https://bugs.chromium.org/p/chromium/issues/detail?id=695031
* https://bugs.webkit.org/show_bug.cgi?id=168720

**Comment by dmurph** [comment]
Huh. So what do we want to happen here?

**Comment by annevk** [comment]
@dmurph the way this works is that XMLHttpRequest invokes the URL parser during `open()`. And that ends up storing a cloned `Blob` object on the returned URL record: https://url.spec.whatwg.org/#concept-url-parser. That URL record gets passed to Fetch at some later point which uses the cloned `Blob` object.
