### ISSUE TITLE
Remove any headers

### ISSUE THREAD

**Issue by tinspin** [whatwg/xhr#83]
I would like to be able to remove any headers from the XHR request when sending to the same origin.

See: https://bugs.webkit.org/show_bug.cgi?id=160432

**Comment by annevk** [comment]
I see @youennf pointed you here, but we don't really extend XMLHttpRequest anymore. It's in maintenance mode. https://github.com/whatwg/fetch/ still gets new features, though as was pointed out to you, many of the headers you want control over are set at the network layer and it's unlikely we'd give direct access over those to developers.

Are you using H2?

**Comment by tinspin** [comment]
Do you mean HTTP/2? If so no.

I want to use XHR.

Why can't developers choose which headers they send to their own servers?

Have you googled "XHR remove header"?

**Comment by annevk** [comment]
As I said, we're no longer adding new features to XMLHttpRequest. I have seen those stackoverflow posts before, and with `fetch()` the situation is a little clearer, but some headers just don't make sense to remove and others are added at a much later stage so would require a specialized API. We could add such a specialized API, but the demand hasn't been that great, despite the couple Google hits.

**Comment by annevk** [comment]
If you know specifically which headers you want to control and why they are a problem you can file an issue against Fetch and we'll consider addressing it. But we're not going to change the API surface for XMLHttpRequest.
