### ISSUE TITLE
Consider adding toJSON to FormData

### ISSUE THREAD

**Issue by annevk** [whatwg/xhr#84]
See https://github.com/whatwg/html/issues/1667 for context. Idea was inspired by a suggestion from @rianby64.

Difficulties: blobs/files (have name, value, filename); multiple keys (use array for values?).

**Comment by rianby64** [comment]
@annevk Thanks a lot!

I've a simple question: the result of ```toJSON()``` should be a mirror of the [fd iterator](https://xhr.spec.whatwg.org/#dom-formdata)?

Please, check [this repo](https://github.com/rianby64/html-toJSON-example), specially the [case1.html](https://github.com/rianby64/html-toJSON-example/blob/master/case1.html#L32)

Critics are welcome! :smile:

**Comment by annevk** [comment]
I guess the problem is that JSON doesn't support arbitrary objects or byte sequences and reading `Blob` cannot be done synchronously, so I'm not sure `toJSON()` actually makes sense here.

It would work for `URLSearchParams`, but not this API.

**Comment by rianby64** [comment]
Right. The [example 9](https://www.w3.org/TR/html-json-forms/) may give us an idea...

```html
EXAMPLE 9: Files
<form enctype='application/json'>
  <input type='file' name='file' multiple>
</form>

// assuming the user has selected two text files, produces:
{
    "file": [
        {
            "type": "text/plain",
            "name": "dahut.txt",
            "body": "REFBQUFBQUFIVVVVVVVVVVVVVCEhIQo="
        },
        {
            "type": "text/plain",
            "name": "litany.txt",
            "body": "SSBtdXN0IG5vdCBmZWFyLlxuRmVhciBpcyB0aGUgbWluZC1raWxsZXIuCg=="
        }
    ]
}
```

However, it's desirable to see if [JSON standard](http://jsonapi.org/format/) defines the behavior for uploading files. I couldn't find anything that cares about file uploading.

**Comment by annevk** [comment]
The problem with that is that `toJSON()` is synchronous and reading files isn't really.

**Comment by rianby64** [comment]
Well, that's news to me. @annevk , please, can you advice me some info about the "reading files process"?

**Comment by annevk** [comment]
@rianby64 try to extract data from a Blob or File object. https://w3c.github.io/FileAPI/ has details.

**Comment by rianby64** [comment]
Thanks a lot, @annevk !

Next. If the reading process is async, should we return a promise? This behavior adds extra complexity... something like

```javascript
form.addEventListener('submit', e => {
  var fd = new FormData(e.target);

  fd.toJSON().then(obj => {
    // here obj has the form's content?
  });

});
```

Not sure if this looks intuitively.
I'll read about Blob/File and then give you some examples...

**Comment by annevk** [comment]
It's probably not useful to offer a standardized API here. Servers can deal with multipart/form-data just fine and JSON doesn't offer that much benefit over it. (Besides, we'd have to serialize the JSON too to transmit it.)

**Comment by rianby64** [comment]
Maybe the function's name is incorrect? What about if name it something like ```toObject()``` ?

**Comment by annevk** [comment]
Yeah, see https://github.com/whatwg/url/issues/143 for that argument.

**Comment by rianby64** [comment]
A... )))))) yeap... my example for ```toJSON()``` looks like sugar over the ```FormData[iterator]``` that probably will not add a significant value to the standard. As quoted @domenic such transformations fit into a library.
