### ISSUE TITLE
What with dat code? He not work :(

### ISSUE THREAD

**Issue by Pulzar1989** [whatwg/xhr#91]
if(optionLocs[index][0] <= scrollTop && scrollTop <= optionLocs[index][1]){
					if(direction == "up"){
						$("#"+id).addClass("active");
						$("#"+optionLocs[index+1][2]).removeClass("active");
					} else if(index > 0) {
						$("#"+id).addClass("active");
						$("#"+optionLocs[index-1][2]).removeClass("active");
					} else if(direction == undefined){
						$("#"+id).addClass("active");
					}
					$.each(optionLocs, function(i){
						if(id != optionLocs[i][2]){
							console.log(i);
							$("#"+optionLocs[i][2]).removeClass("active");
						}
					});
				}
			};

**Comment by Pulzar1989** [comment]
???

**Comment by annevk** [comment]
Please use https://stackoverflow.com/ for web development questions. This is not the place.
