### ISSUE TITLE
send() flag not unset in open() - send() - open() call sequence

### ISSUE THREAD

**Issue by berniegp** [whatwg/xhr#94]
The xhr specification does not specify that the `send() flag` should be unset when making this sequence of calls:

1. `xhr.open()`
2. `xhr.send()` <--- sets the `send() flag`
3. `xhr.open()`

This means, based on the spec, that calls to `setRequestHeader()` (and some other methods) should fail at this stage because the `send() flag` should still be set.

The spec for the [open() method](https://xhr.spec.whatwg.org/#the-open()-method) has this:
```
10. Terminate the request. 
```

However, this does not unset the `send() flag`. Compare this to the steps of the `abort()` method:
```
1. Terminate the request. 
2. If state is either opened with the send() flag set, headers received, or loading, run the request error steps for event abort. 
```

The "request error steps" mentioned in step 2 takes care of unsetting the `send() flag`.

The test [open-send-open](https://github.com/w3c/web-platform-tests/blob/master/XMLHttpRequest/open-send-open.htm) runs this same sequence of events, so I expect that the intended behavior is to allow this usage scenario and unset the `send() flag`.

**Comment by berniegp** [comment]
The [terminate the request step](https://xhr.spec.whatwg.org/#terminate-the-request) is:
```
To terminate the request, terminate the fetch algorithm operated by the XMLHttpRequest object with reason fatal. 
```
This does not unset the `send() flag`.

**Comment by berniegp** [comment]
I suggest changing the terminate step to:

```
To terminate the request, terminate the fetch algorithm operated by the XMLHttpRequest object with reason fatal and unset the send() flag.
```

**Comment by berniegp** [comment]
To fix both issues and be in-line with browser behavior, perhaps this would work for abort():

```
1. Let sent be the state of the send() flag.

2. Terminate the request.
// This unsets the send() flag

3. Unset the request URL
// To detect a call to open() during the next step

4. If state is either opened with sent set, headers received, or loading, run the request error steps for event abort.

3. If the request URL is unset, set state to unsent.
```

**Comment by annevk** [comment]
We could also just unset the send() flag in a different step, e.g., step 11 (where we also reset other state).

**Comment by berniegp** [comment]
@annevk I have discovered new information in #88 which invalidates some of my proposed changes. That other issue should probably be resolved before this one can addressed.

**Comment by annevk** [comment]
Given the tentative resolution in #88, how do you feel about unsetting the flag in step 11?

Also, how would you like to appear in the Acknowledgments section?

**Comment by berniegp** [comment]
Yes I think unsetting the flag in step 11 would work. There would then be 3 ways to unset the send() flag:

1. calling open()
2. calling abort()
3. letting the request finish (response end-of-body or request error)

I'd be glad to appear in the acknowledgements section as Bertrand Guay-Paquet.

**Comment by annevk** [comment]
Thanks!
