### ISSUE TITLE
Entry settings object usage is probably wrong

### ISSUE THREAD

**Issue by domenic** [whatwg/xhr#98]
At least, when I scanned Chrome for usages of the entry settings object, I didn't see anything about XHR in there, and if I recall @bzbarsky did a similar thing for Gecko.

I can try to write up tests for this and submit a patch if my suspicions are confirmed.

**Comment by domenic** [comment]
Actually, I don't think there's any need to write tests here, as it's impossible for entry/incumbent/relevant/current to mismatch in whether or not they are a Window object. We can just change these all to relevant-of-context-object, or to current, at our leisure. I guess relevant-of-context-object is the way to go.

**Comment by annevk** [comment]
Current seems nicer? But entry somehow seems purer. It would be a little annoying to change this before the Bikeshed conversion though. Do not want to rebase that across.

**Comment by domenic** [comment]
Yeah happy to wait until after.

**Comment by domenic** [comment]
We used relevant for fetch and service worker in this situation, since that's what HTML recommends for consistency.

**Comment by bzbarsky** [comment]
Fwiw, in terms of implementation Gecko stores the "is an XHR for a window" state during the XHR constructor, by looking at the constructor's current global.  But yes, I agree that all of these should be equivalent.
